name: CI Playground

on:
  push:
    branches:
      - ci-playground

jobs:
  init-submodules:
    runs-on: ubuntu-22.04
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v2

      - name: Retrieve cache
        id: retrieve-cache
        uses: actions/cache@v3
        with:
          path: |
            .git
            binutils
            dejagnu
            gcc
            gdb
            glibc
            musl
            newlib
            pk
            qemu
          key: submodules


      - name: Init gcc
        run: |
          cd gcc
          git checkout master
          git pull

      - name: Search for most recent valid hash
        run: |
          pip install pygithub
          python ./scripts/get-most-recent-ci-hash.py -hash ef3bbc69d15707e4db6e2f198c621effb636cc26 -token ${{ secrets.GITHUB_TOKEN }}

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-frequent.yaml
          workflow_conclusion: ""
          branch: daily-ci
          name: gcc-linux-rv32gc-ilp32d-ef3bbc69d15707e4db6e2f198c621effb636cc26-non-multilib-report.log
          search_artifacts: true
          if_no_artifact_found: fail

      - name: Old artifact
        id: download-old-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-frequent.yaml
          workflow_conclusion: ""
          branch: daily-ci
          name: gcc-linux-rv32gc-ilp32d-b621883620b127caf20e88e59fa73e666960013e-non-multilib-report.log
          search_artifacts: true
          if_no_artifact_found: fail

      - name: run script
        run: |
          ./scripts/compare-testsuite-log -plog gcc-linux-rv32gc-ilp32d-b621883620b127caf20e88e59fa73e666960013e-non-multilib-report.log \
            -phash b621883620b127caf20e88e59fa73e666960013e \
            -clog gcc-linux-rv32gc-ilp32d-ef3bbc69d15707e4db6e2f198c621effb636cc26-non-multilib-report.log \
            -chash ef3bbc69d15707e4db6e2f198c621effb636cc26 \
            -o out.md
          cat out.md

      - name: trim script output
        run: |
          head -100 out.md > test.md

      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: test.md
          update_existing: true

      - name: run script (same hash)
        run: |
          ./scripts/compare-testsuite-log \
            -plog gcc-linux-rv32gc-ilp32d-ef3bbc69d15707e4db6e2f198c621effb636cc26-non-multilib-report.log \
            -phash ef3bbc69d15707e4db6e2f198c621effb636cc26-same \
            -clog gcc-linux-rv32gc-ilp32d-ef3bbc69d15707e4db6e2f198c621effb636cc26-non-multilib-report.log \
            -chash ef3bbc69d15707e4db6e2f198c621effb636cc26-same \
            -o out.md
          cat out.md

      - name: trim script output (same hash)
        run: |
          head -100 out.md > test.md

      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: test.md
          update_existing: true
