name: CI Playground

on:
  push:
    branches:
      - ci-playground

jobs:
  init-submodules:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-frequent.yaml
          branch: daily-ci
          name: gcc-linux-rv32gc-ilp32d-a0cb65d34cc-non-multilib-report.log
          search_artifacts: true
          if_no_artifact_found: fail
