name: Build-Frequent

on:
  push:
    branches:
      - daily-ci
  pull_request:
    branches:
      - daily-ci
  schedule:
    # Run daily
    - cron: 0 0 * * *
  workflow_dispatch:
    branches:
      - daily-ci
    inputs:
      gcchash:
        description: 'GCC Hash'
        required: true

jobs:
  init-submodules:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Retrieve cache
        id: retrieve-cache
        uses: actions/cache@v3
        with:
          path: |
            .git
            binutils
            dejagnu
            gcc
            gdb
            glibc
            musl
            newlib
            pk
            qemu
          key: submodules

      - name: Initalize submodules cache
        if: steps.retrieve-cache.outputs.cache-hit != 'true'
        run: |
          git submodule init
          rm -rf gcc
          git clone git://gcc.gnu.org/git/gcc.git
          git submodule update --recursive --progress --recommend-shallow

      - name: Get GCC hash
        id: gcc-hash
        run: |
          cd gcc
          git checkout master
          git pull
          if [ "${{ github.event.inputs.gcchash }}" == "" ]; then
            export GCCHASH=$(git rev-parse --short HEAD)
          else
            export GCCHASH=${{ github.event.inputs.gcchash }}
          fi
          echo $GCCHASH
          echo "gcchash=$GCCHASH" >> "$GITHUB_OUTPUT"

      - name: Cache submodules
        if: steps.retrieve-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: |
            .git
            binutils
            dejagnu
            gcc
            gdb
            glibc
            musl
            newlib
            pk
            qemu
          key: submodules

      - name: Upload git cache
        uses: actions/upload-artifact@v3
        with:
          name: gcc-sources-${{ inputs.gcchash }}
          path: |
            .git
            binutils
            dejagnu
            gcc
            gdb
            glibc
            musl
            newlib
            pk
            qemu
          retention-days: 5

    outputs:
      gcchash: ${{ steps.gcc-hash.outputs.gcchash }}

  creg: # Check Regressions. Short name so I can see the matrix string in github
    needs: [init-submodules]
    strategy:
      fail-fast: false
      matrix:
        mode:   [newlib, linux, musl]
        target: [rv32gc-ilp32d, rv64gc-lp64d]
        multilib: [non-multilib]
        exclude:
          - mode: musl
            target: rv32gc-ilp32d
          - mode: musl
            multilib: multilib
          - target: rv32gc-ilp32d
            multilib: multilib
    uses: ./.github/workflows/regression-runner.yaml
    with:
      mode: ${{ matrix.mode }}
      target: ${{ matrix.target }}
      gcchash: ${{ needs.init-submodules.outputs.gcchash }}
      multilib: ${{ matrix.multilib }}

  generate-issues:
    if: always()
    runs-on: ubuntu-22.04
    needs: [creg]
    steps:
      - name: Generate summary
        run: |
          echo Filing issue...
