name: CI Playground

on:
  push:
    branches:
      - ci-playground

jobs:
  init-submodules:
    runs-on: ubuntu-22.04
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v2

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-frequent.yaml
          workflow_conclusion: ""
          branch: daily-ci
          name: gcc-linux-rv32gc-ilp32d-a0cb65d34cc-non-multilib-report.log
          search_artifacts: true
          if_no_artifact_found: fail

      - name: Old artifact
        id: download-old-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-frequent.yaml
          workflow_conclusion: ""
          branch: daily-ci
          name: gcc-linux-rv32gc-ilp32d-cc035c5d8672f87dc8c2756d9f8367903aa72d93-non-multilib-report.log
          search_artifacts: true
          if_no_artifact_found: fail

      - name: run script
        run: |
          ./scripts/compare-testsuite-log -plog gcc-linux-rv32gc-ilp32d-cc035c5d8672f87dc8c2756d9f8367903aa72d93-non-multilib-report.log \
            -phash cc035c5d8672f87dc8c2756d9f8367903aa72d93 \
            -clog gcc-linux-rv32gc-ilp32d-a0cb65d34cc-non-multilib-report.log \
            -chash a0cb65d34cc \
            -o out.md
          cat out.md

      - name: trim script output
        run: |
          head -50 out.md > test.md

      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: test.md
          update_existing: true

      - name: run script (same hash)
        run: |
          ./scripts/compare-testsuite-log -plog gcc-linux-rv32gc-ilp32d-a0cb65d34cc-non-multilib-report.log \
            -phash a0cb65d34cc-same \
            -clog gcc-linux-rv32gc-ilp32d-a0cb65d34cc-non-multilib-report.log \
            -chash a0cb65d34cc-same \
            -o out.md
          cat out.md

      - name: trim script output (same hash)
        run: |
          head -50 out.md > test.md

      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: test.md
          update_existing: true
