on:
  workflow_call:
    inputs:
      mode:
        required: true
        type: string
      target:
        required: true
        type: string
      gcchash:
        required: true
        type: string
      multilib:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-22.04
    environment: production
    steps:
      - uses: actions/checkout@v2

      - name: Load submodules from cache
        uses: actions/cache@v3
        id: restore-build
        with:
          path: |
            binutils
            dejagnu
            gcc
            gdb
            glibc
            llvm
            musl
            newlib
            pk
            qemu
          key: submodules

      - name: Checkout gcc hash
        run: |
          cd gcc
          git fetch
          git checkout ${{ inputs.gcchash }}

      - name: Install dependencies
        run: sudo ./.github/setup-apt.sh

      - name: Configure
        run: |
          mkdir build
          cd build
          TARGET_TUPLE=($(echo ${{ inputs.target }} | tr "-" "\n"))
          CONFIGURE_TOOLCHAIN="../configure --prefix=$(pwd) --with-arch=${TARGET_TUPLE[0]} --with-abi=${TARGET_TUPLE[1]}"
          if [ "${{ inputs.multilib }}" == "multilib" ]; then
            $CONFIGURE_TOOLCHAIN --enable-multilib
          else
            $CONFIGURE_TOOLCHAIN
          fi

      - name: Make gcc
        run: |
          cd build
          make -j $(nproc) ${{ inputs.mode }}

      - name: Zip files
        run: |
          zip -r bin.zip build/bin
          zip -r stage2.zip build/build-gcc-${{ inputs.mode }}-stage2

      - name: Upload binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: gcc-${{ inputs.mode }}-${{ inputs.target }}-${{ inputs.gcchash }}-${{ inputs.multilib }}
          path: |
            bin.zip
          retention-days: 5

      - name: Upload stage2 artifact
        uses: actions/upload-artifact@v3
        with:
          name: gcc-${{ inputs.mode }}-${{ inputs.target }}-${{ inputs.gcchash }}-${{ inputs.multilib }}-stage2
          path: |
            stage2.zip
          retention-days: 5

  test:
    if: ${{ inputs.mode != 'musl' }}
    runs-on: ubuntu-22.04
    environment: production
    needs: [build]
    steps:
      - uses: actions/checkout@v2

      - name: Load submodules from cache
        uses: actions/cache@v3
        id: restore-build
        with:
          path: |
            binutils
            dejagnu
            gcc
            gdb
            glibc
            llvm
            musl
            newlib
            pk
            qemu
          key: submodules

      - name: Checkout gcc hash
        run: |
          cd gcc
          git fetch
          git checkout ${{ inputs.gcchash }}

      - name: Install dependencies
        run: sudo ./.github/setup-apt.sh

      - name: Configure
        run: |
          mkdir build
          cd build
          TARGET_TUPLE=($(echo ${{ inputs.target }} | tr "-" "\n"))
          CONFIGURE_TOOLCHAIN="../configure --prefix=$(pwd) --with-arch=${TARGET_TUPLE[0]} --with-abi=${TARGET_TUPLE[1]}"
          if [ "${{ inputs.multilib }}" == "multilib" ]; then
            $CONFIGURE_TOOLCHAIN --enable-multilib
          else
            $CONFIGURE_TOOLCHAIN
          fi

      - name: Touch sources
        run: |
          cd gcc
          find . -exec touch {} +
          touch .git

      - name: Restore binaries
        uses: actions/download-artifact@v3
        with:
          name: gcc-${{ inputs.mode }}-${{ inputs.target }}-${{ inputs.gcchash }}-${{ inputs.multilib }}

      - name: Restore stage2
        uses: actions/download-artifact@v3
        with:
          name: gcc-${{ inputs.mode }}-${{ inputs.target }}-${{ inputs.gcchash }}-${{ inputs.multilib }}-stage2

      - name: Unzip artifacts
        run: |
          unzip bin.zip
          unzip stage2.zip

      - name: Touch build
        run: |
          cd build
          find . -exec touch -d "+2 days" {} +

      - name: Touch makefile
        run: |
          cd build
          touch -d "+2 days" Makefile

      - name: Fake stamps
        run: |
          mkdir build/stamps
          cd build/stamps
          touch -d "+2 days" check-write-permission
          touch -d "+2 days" build-binutils-${{ inputs.mode }}
          touch -d "+2 days" build-gcc-${{ inputs.mode }}-stage1
          touch -d "+2 days" build-gcc-${{ inputs.mode }}-stage2
          touch -d "+2 days" build-gdb-${{ inputs.mode }}
          touch -d "+2 days" build-${{ inputs.mode }}-nano
          touch -d "+2 days" build-${{ inputs.mode }}
          touch -d "+2 days" merge-${{ inputs.mode }}-nano

      - name: Print timestamps
        run: |
          ls -la .

      - name: Print GCC timestamps
        run: |
          cd gcc && ls -la .

      - name: Print build timestamps
        run: |
          cd build && ls -la .
          cd stamps && ls -la .

      - name: Build stamp (should be instant)
        run: |
          cd build
          make -d stamps/build-gcc-${{ inputs.mode }}-stage2

      - name: Run testsuite
        run: |
          cd build
          make -j $(nproc) report-${{ inputs.mode }} || true

      - name: Save results
        run: |
          cd build
          make -j $(nproc) report | gcc-${{ inputs.mode }}-${{ inputs.target }}-${{ inputs.gcchash }}-${{ inputs.multilib }}-report.log || true

      - name: Upload stage2 artifact
        uses: actions/upload-artifact@v3
        with:
          name: gcc-${{ inputs.mode }}-${{ inputs.target }}-${{ inputs.gcchash }}-${{ inputs.multilib }}-report
          path: |
            gcc-${{ inputs.mode }}-${{ inputs.target }}-${{ inputs.gcchash }}-${{ inputs.multilib }}-report.log
          retention-days: 90
